version: '2'

services:
  database:
    image: postgres:10
    restart: always
    healthcheck:
      timeout: 30s
      retries: 3
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=demodb
      - POSTGRES_PASSWORD=admin
    ports:
      - 5434:5432


